# Generated by Django 5.2.1 on 2025-05-08 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=50, verbose_name='Наименование файла')),
                ('file', models.ImageField(upload_to='courses/images/', verbose_name='Файл')),
                ('random_int', models.IntegerField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Рандомное значение')),
                ('load_time', models.DateTimeField(auto_now_add=True, verbose_name='Время сохранения')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ('-id',),
            },
        ),
    ]
