# Generated by Django 5.2.1 on 2025-05-08 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='random_int',
            field=models.IntegerField(default=954, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Рандомное значение'),
        ),
    ]
